// --- Citazioni aggiuntive (parte 1) ---
{ text: "Il successo non consiste nel non commettere errori, ma nel non ripeterli due volte.", author: "George Bernard Shaw" },
{ text: "Non smettere mai di sorridere, anche quando sei triste, perché non sai chi potrebbe innamorarsi del tuo sorriso.", author: "Gabriel García Márquez" },
{ text: "Le grandi cose non sono fatte per impulso, ma da una serie di piccole cose messe insieme.", author: "Vincent Van Gogh" },
{ text: "Nessun vento è favorevole per il marinaio che non sa dove andare.", author: "Seneca" },
{ text: "Chi ha un perché per vivere può sopportare quasi ogni come.", author: "Friedrich Nietzsche" },
{ text: "La libertà non consiste nel fare ciò che si vuole, ma nel volere ciò che si deve.", author: "Immanuel Kant" },
{ text: "Le ferite che non si vedono sono le più profonde.", author: "William Shakespeare" },
{ text: "Chi non osa nulla, non spera nulla.", author: "Friedrich Schiller" },
{ text: "L’unico vero fallimento è non provarci mai.", author: "Anonimo" },
{ text: "Non si vede bene che col cuore. L’essenziale è invisibile agli occhi.", author: "Antoine de Saint-Exupéry" },
{ text: "Ogni uomo è l’architetto del proprio destino.", author: "Appio Claudio Cieco" },
{ text: "La mente è come un paracadute: funziona solo se si apre.", author: "Albert Einstein" },
{ text: "Non è la vita ad essere breve, ma noi che la rendiamo tale.", author: "Seneca" },
{ text: "La musica può cambiare il mondo perché può cambiare le persone.", author: "Bono Vox" },
{ text: "La paura è il peggior nemico dell’uomo.", author: "Anonimo" },
{ text: "Il vero amore comincia quando non ci si aspetta nulla in cambio.", author: "Antoine de Saint-Exupéry" },
{ text: "Non è la montagna che conquistiamo, ma noi stessi.", author: "Sir Edmund Hillary" },
{ text: "Ogni giorno è una nuova opportunità per cambiare la tua vita.", author: "Anonimo" },
{ text: "Il silenzio è la forma più perfetta della parola.", author: "Pitagora" },
{ text: "Chi teme di soffrire soffre già di ciò che teme.", author: "Michel de Montaigne" },
{ text: "Non è mai troppo tardi per imparare qualcosa di nuovo.", author: "Anonimo" },
{ text: "L’educazione è l’arma più potente che si possa usare per cambiare il mondo.", author: "Nelson Mandela" },
{ text: "La vera felicità costa poco; se è cara, non è di buona qualità.", author: "François-René de Chateaubriand" },
{ text: "Non ci sono scorciatoie per i luoghi che valgono la pena di essere raggiunti.", author: "Beverly Sills" },
{ text: "Chi non sa dove andare, rischia di non arrivarci mai.", author: "Anonimo" },
{ text: "La mente domina il corpo, non il contrario.", author: "Socrate" },
{ text: "L’amore non consiste nel guardarsi a vicenda, ma nel guardare insieme nella stessa direzione.", author: "Antoine de Saint-Exupéry" },
{ text: "Ogni difficoltà superata è una vittoria dell’anima.", author: "Anonimo" },
{ text: "Il modo migliore per predire il futuro è crearlo.", author: "Peter Drucker" },
{ text: "Non importa quanto vai piano, l’importante è non fermarsi.", author: "Confucio" },
{ text: "L’esperienza è semplicemente il nome che diamo ai nostri errori.", author: "Oscar Wilde" },
{ text: "Non c’è niente di più potente di un’idea il cui tempo è arrivato.", author: "Victor Hugo" },
{ text: "Ogni sogno realizzato è un sogno per cui qualcuno ha lottato.", author: "Anonimo" },
{ text: "La pace inizia con un sorriso.", author: "Madre Teresa di Calcutta" },
{ text: "Le parole gentili possono essere brevi e facili da dire, ma la loro eco è infinita.", author: "Madre Teresa di Calcutta" },
{ text: "Il talento fa vincere le partite, ma il lavoro di squadra e l’intelligenza fanno vincere i campionati.", author: "Michael Jordan" },
{ text: "L’unico modo per evitare le critiche è non fare nulla, non dire nulla e non essere nulla.", author: "Aristotele" },
{ text: "Non lasciare che la paura decida il tuo futuro.", author: "Anonimo" },
{ text: "Ogni persona che incontri sta combattendo una battaglia di cui non sai nulla. Sii gentile.", author: "Platone" },
{ text: "L’unico uomo che non sbaglia mai è quello che non fa mai nulla.", author: "Theodore Roosevelt" },
{ text: "Sii te stesso; tutti gli altri sono già occupati.", author: "Oscar Wilde" },
{ text: "Non seguire il sentiero. Vai invece dove non c’è un sentiero e lascia una traccia.", author: "Ralph Waldo Emerson" },
{ text: "Il pessimismo porta alla debolezza, l’ottimismo alla potenza.", author: "William James" },
{ text: "Il tempo che ti diverte è tempo ben speso.", author: "Bertrand Russell" },
{ text: "Il vero eroe non è colui che non cade mai, ma colui che si rialza sempre.", author: "Anonimo" },
{ text: "La conoscenza è potere.", author: "Francis Bacon" },
{ text: "Non c’è progresso senza cambiamento.", author: "Henry Ford" },
{ text: "L’immaginazione governa il mondo.", author: "Napoleone Bonaparte" },
{ text: "Un giorno senza sorriso è un giorno perso.", author: "Charlie Chaplin" },
{ text: "Chi semina amore raccoglie felicità.", author: "Anonimo" },
{ text: "Non esiste notte così lunga da impedire al sole di risorgere.", author: "Anonimo" },
{ text: "Non puoi cambiare il vento, ma puoi orientare le vele.", author: "Aristotele" },
{ text: "La bellezza salverà il mondo.", author: "Fëdor Dostoevskij" },
{ text: "L’unico limite alla nostra realizzazione di domani saranno i nostri dubbi di oggi.", author: "Franklin D. Roosevelt" },
{ text: "Non aspettare il momento perfetto, prendilo e rendilo tale.", author: "Anonimo" },
{ text: "Chi desidera vedere l’arcobaleno deve imparare ad amare la pioggia.", author: "Paulo Coelho" },
{ text: "Il valore di un uomo si misura in base a quanta verità riesce a dire.", author: "Friedrich Nietzsche" },
{ text: "L’amicizia raddoppia le gioie e divide le angosce a metà.", author: "Francesco Bacone" },
{ text: "L’amore è composto da un’unica anima che abita due corpi.", author: "Aristotele" },
{ text: "Tutti pensano a cambiare il mondo, ma nessuno pensa a cambiare se stesso.", author: "Lev Tolstoj" },
{ text: "Le persone forti non abbattono gli altri, li sollevano.", author: "Anonimo" },
{ text: "La mente crea la realtà.", author: "Buddha" },
{ text: "Dove non c’è lotta, non c’è forza.", author: "Oprah Winfrey" },
{ text: "Il mondo è pieno di cose magiche, pazientemente in attesa che i nostri sensi si affilino.", author: "W.B. Yeats" },
{ text: "Ogni nuova amicizia è una nuova avventura.", author: "Anon
