// Questo file definisce l'array delle citazioni. Verrà caricato nel file index.html.

const quotes = [
    { text: "La semplicità è l'ultima sofisticazione.", author: "Leonardo da Vinci" },
    { text: "Il futuro appartiene a coloro che credono nella bellezza dei propri sogni.", author: "Eleanor Roosevelt" },
    { text: "Non avrai mai un secondo per fare una buona prima impressione.", author: "Coco Chanel" },
    { text: "La vita è quello che succede mentre sei impegnato a fare altri progetti.", author: "John Lennon" },
    { text: "Sii il cambiamento che vuoi vedere nel mondo.", author: "Mahatma Gandhi" },
    { text: "Non smettere mai di imparare, perché la vita non smette mai di insegnare.", author: "Anonimo" },
    { text: "Il successo non è la chiave della felicità. La felicità è la chiave del successo.", author: "Albert Schweitzer" },
    { text: "L'unico modo per fare un ottimo lavoro è amare quello che fai.", author: "Steve Jobs" },
    { text: "Siamo tutti nel fosso, ma alcuni di noi stanno guardando le stelle.", author: "Oscar Wilde" },
    { text: "La misura di ciò che siamo è ciò che facciamo con ciò che abbiamo.", author: "Vince Lombardi" },
    { text: "La felicità è quando ciò che pensi, ciò che dici e ciò che fai sono in armonia.", author: "Mahatma Gandhi" },
    { text: "Un viaggio di mille miglia comincia con un singolo passo.", author: "Lao Tzu" },
    { text: "Fai della tua vita un sogno, e di un sogno, una realtà.", author: "Antoine de Saint-Exupéry" },
    { text: "Il modo per iniziare è smettere di parlare e iniziare a fare.", author: "Walt Disney" },
    { text: "La vera misura di un uomo non si vede nei suoi momenti di agio, ma nei momenti di sfida e di controversia.", author: "Martin Luther King Jr." },
    { text: "Le difficoltà rafforzano la mente, proprio come il lavoro rafforza il corpo.", author: "Seneca" },
    { text: "Non contare i giorni, fai in modo che i giorni contino.", author: "Muhammad Ali" },
    { text: "Non arrenderti, il meglio deve ancora venire.", author: "Anonimo" },
    { text: "Cambia i tuoi pensieri e cambierai il tuo mondo.", author: "Norman Vincent Peale" },
    { text: "La creatività è intelligenza che si diverte.", author: "Albert Einstein" },
    { text: "Il coraggio non è l'assenza di paura, ma il trionfo su di essa.", author: "Nelson Mandela" },
    { text: "Il successo è la somma di piccoli sforzi ripetuti giorno dopo giorno.", author: "Robert Collier" },
    { text: "Ogni mattina abbiamo due scelte: continuare a dormire con i nostri sogni, o svegliarci e inseguirli.", author: "Anonimo" },
    { text: "L'unica limitazione è quella che ti poni nella tua mente.", author: "Napoleon Hill" },
    { text: "Se puoi sognarlo, puoi farlo.", author: "Walt Disney" },
    { text: "Le persone non falliscono, semplicemente rimandano il successo.", author: "Anonimo" },
    { text: "La pazienza è la chiave che apre ogni porta.", author: "Proverbio" },
    { text: "Il momento migliore per piantare un albero era vent'anni fa. Il secondo miglior momento è ora.", author: "Proverbio Cinese" },
    { text: "Non è forte chi non cade, ma chi cade e si rialza.", author: "Goethe" },
    { text: "Non cercare di diventare un uomo di successo, ma piuttosto cerca di diventare un uomo di valore.", author: "Albert Einstein" },
    { text: "La logica ti porterà da A a B. L'immaginazione ti porterà ovunque.", author: "Albert Einstein" },
    { text: "L'unica cosa peggiore che iniziare qualcosa e fallire... è non iniziare affatto.", author: "Seth Godin" },
    { text: "Non è mai troppo tardi per essere ciò che avresti potuto essere.", author: "George Eliot" },
    { text: "Le tue azioni parlano così forte che non riesco a sentire quello che dici.", author: "Ralph Waldo Emerson" },
    { text: "Sii sempre te stesso. Chi altro potresti essere?", author: "Anonimo" },
    { text: "La vera libertà è non avere niente da nascondere.", author: "Anonimo" },
    { text: "Quando la vita ti dà i limoni, fai la limonata.", author: "Elbert Hubbard" },
    { text: "Il dubbio uccide più sogni del fallimento.", author: "Suzy Kassem" },
    { text: "Fissa il tuo sguardo sulle stelle e i tuoi piedi a terra.", author: "Theodore Roosevelt" },
    { text: "Non aspettare. Non ci sarà mai un momento perfetto.", author: "Napoleon Hill" },
    { text: "L'insuccesso è solo l'opportunità di ricominciare con più intelligenza.", author: "Henry Ford" },
    { text: "Non si può attraversare il mare semplicemente stando lì a guardare l'acqua.", author: "Rabindranath Tagore" },
    { text: "La mente è tutto. Ciò che pensi, tu diventi.", author: "Buddha" },
    { text: "Il nostro più grande difetto è la rinuncia. Il modo più sicuro per avere successo è riprovare sempre.", author: "Thomas A. Edison" },
    { text: "L'arte di vivere è come un'opera teatrale: non è tanto quanto dura, ma come viene recitata.", author: "Seneca" },
    { text: "La differenza tra un giorno buono e un giorno cattivo sta nel tuo atteggiamento.", author: "Anonimo" },
    { text: "Il cambiamento è la legge della vita. E quelli che guardano solo al passato o al presente sono sicuri di perdersi il futuro.", author: "John F. Kennedy" },
    { text: "La vita non è trovare se stessi. La vita è creare se stessi.", author: "George Bernard Shaw" },
    { text: "Il prezzo del successo è il duro lavoro, la dedizione al lavoro e la determinazione.", author: "Vince Lombardi" },
    { text: "Fai ciò che devi fare finché non puoi fare ciò che vuoi fare.", author: "Oprah Winfrey" },
    { text: "Il successo è camminare da un fallimento all'altro senza perdere l'entusiasmo.", author: "Winston Churchill" },
    { text: "La disciplina è il ponte tra gli obiettivi e la realizzazione.", author: "Jim Rohn" },
    { text: "Non giudicare ogni giorno dalla raccolta che fai, ma dai semi che pianti.", author: "Robert Louis Stevenson" },
    { text: "La vita è per il 10% ciò che ti accade e per il 90% come reagisci.", author: "Charles R. Swindoll" },
    { text: "La vera scoperta non consiste nel trovare nuove terre, ma nell'avere nuovi occhi.", author: "Marcel Proust" },
    { text: "Se non lotti per ciò che vuoi, non piangere per ciò che perdi.", author: "Anonimo" },
    { text: "Non si può mai pianificare il futuro dal passato.", author: "Edmund Burke" },
    { text: "Non devi essere grande per iniziare, ma devi iniziare per essere grande.", author: "Zig Ziglar" },
    { text: "La gioia è un'azione. È una scelta. Non è una cosa che succede e basta.", author: "Anonimo" },
    { text: "Il segreto per andare avanti è iniziare.", author: "Mark Twain" },
    { text: "Credi di potercela fare e sei a metà strada.", author: "Theodore Roosevelt" },
    { text: "Le persone di successo fanno ciò che i non-riusciti non sono disposti a fare.", author: "Jim Rohn" },
    { text: "Il cambiamento è difficile all'inizio, disordinato nel mezzo e meraviglioso alla fine.", author: "Robin Sharma" },
    { text: "Il valore di un'idea risiede nel suo utilizzo.", author: "Thomas Edison" },
    { text: "Il mondo si sposta in avanti non solo per la spinta degli eroi, ma per il totale di piccole spinte di ogni onesto lavoratore.", author: "Helen Keller" },
    { text: "Non accontentarti di quello che ti serve. Lotta per quello che meriti.", author: "Anonimo" },
    { text: "La felicità è un modo di viaggiare, non una destinazione.", author: "Anonimo" },
    { text: "Non è mai troppo tardi per un nuovo inizio nella tua vita.", author: "Anonimo" },
    { text: "La cosa più difficile è la decisione di agire, il resto è solo tenacia.", author: "Amelia Earhart" },
    { text: "Non si può scoprire l'oceano a meno che non si abbia il coraggio di perdere di vista la riva.", author: "André Gide" },
    { text: "Ricorda che non ottenere ciò che vuoi è a volte un colpo di fortuna.", author: "Dalai Lama" },
    { text: "L'immaginazione è più importante della conoscenza.", author: "Albert Einstein" },
    { text: "Non è la specie più forte a sopravvivere, né la più intelligente, ma quella più reattiva al cambiamento.", author: "Charles Darwin" },
    { text: "Se non costruisci il tuo sogno, qualcun altro ti assumerà per costruire il suo.", author: "Dhirubhai Ambani" },
    { text: "La chiave del successo è concentrarsi sugli obiettivi, non sugli ostacoli.", author: "Anonimo" },
    { text: "La vita non ti dà quello che vuoi, ti dà quello per cui lavori.", author: "Anonimo" },
    { text: "Sii come un francobollo: attaccati a una cosa finché non arrivi a destinazione.", author: "Josh Billings" },
    { text: "Non fallisci finché non smetti di provarci.", author: "Anonimo" },
    { text: "Inizia dove sei. Usa quello che hai. Fai quello che puoi.", author: "Arthur Ashe" },
    { text: "Il tuo tempo è limitato, non sprecarlo vivendo la vita di qualcun altro.", author: "Steve Jobs" },
    { text: "Tutto ciò che puoi immaginare è reale.", author: "Pablo Picasso" },
    { text: "Ci sono due modi per vivere la vita: uno è pensare che niente sia un miracolo. L'altro è pensare che ogni cosa sia un miracolo.", author: "Albert Einstein" },
    { text: "Non è importante quanto lentamente vai finché non ti fermi.", author: "Confucio" },
    { text: "La felicità è uno stato d'animo. Dipende da come guardi le cose.", author: "Anonimo" },
    { text: "L'azione è la chiave fondamentale per ogni successo.", author: "Pablo Picasso" },
    { text: "Fai ciò che è giusto, non ciò che è facile.", author: "Anonimo" },
    { text: "La gioia è la forma più semplice di gratitudine.", author: "Karl Barth" },
    { text: "Ogni realizzazione inizia con la decisione di provare.", author: "Gail Devers" },
    { text: "Non si può tornare indietro per cambiare l'inizio, ma si può iniziare dove si è e cambiare il finale.", author: "C.S. Lewis" },
    { text: "La vita è una avventura audace o non è nulla.", author: "Helen Keller" },
    { text: "La mente, una volta allungata da una nuova idea, non torna mai alle sue dimensioni originali.", author: "Oliver Wendell Holmes" },
    { text: "Se vuoi sollevarti, solleva qualcun altro.", author: "Booker T. Washington" },
    { text: "Il modo in cui ci vediamo determina il modo in cui trattiamo gli altri.", author: "Deepak Chopra" },
    { text: "Non c'è scorciatoia per raggiungere un posto che valga la pena raggiungere.", author: "Beverly Sills" },
    { text: "La domanda non è chi mi permetterà; è chi mi fermerà.", author: "Ayn Rand" },
    { text: "Le persone che sono abbastanza folli da pensare di poter cambiare il mondo sono quelle che lo fanno.", author: "Rob Siltanen" },
    { text: "Cadi sette volte, rialzati otto.", author: "Proverbio Giapponese" },
    { text: "La forza non deriva dalla vittoria. Le tue lotte sviluppano i tuoi punti di forza.", author: "Arnold Schwarzenegger" },
    { text: "Scegli di essere ottimista, ti sentirai meglio.", author: "Dalai Lama" },
    { text: "Le idee non durano a lungo. Bisogna fare qualcosa per loro.", author: "Santiago Ramón y Cajal" },
    { text: "Sogna in grande e osa fallire.", author: "Norman Vaughan" },
    { text: "Per avere successo, la tua voglia di successo deve essere più grande della tua paura del fallimento.", author: "Bill Cosby" },
    { text: "Non è la quantità, ma la qualità che conta.", author: "Seneca" },
    { text: "La vita è breve, sorridi finché hai ancora i denti.", author: "Anonimo" },
    { text: "Il tuo unico limite è la tua immaginazione.", author: "Anonimo" },
    { text: "La saggezza è l'arma più affilata.", author: "Rick Riordan" },
    { text: "Sii grato per quello che hai; sarai felice con di più.", author: "Oprah Winfrey" },
    { text: "Il più grande errore che puoi fare nella vita è quello di essere continuamente spaventato di fare un errore.", author: "Elbert Hubbard" },
    { text: "Non rimpiangere mai ciò che ti ha fatto sorridere.", author: "Mark Twain" },
    { text: "La perseveranza è il duro lavoro che fai dopo che ti sei stancato del duro lavoro che hai già fatto.", author: "Newt Gingrich" },
    { text: "Per avere successo devi accettare tutte le sfide che incontri. Non puoi accettare solo quelle che ti piacciono.", author: "Mike Ditka" },
    { text: "Il tempo è la moneta della tua vita. È l'unica moneta che hai, e solo tu puoi decidere come spenderla.", author: "Carl Sandburg" },
    { text: "Per criticare devi avere una profonda conoscenza. Per fare, devi solo sapere.", author: "Oscar Wilde" },
    { text: "Le persone dimenticheranno quello che hai detto, dimenticheranno quello che hai fatto, ma non dimenticheranno mai come le hai fatte sentire.", author: "Maya Angelou" },
    { text: "Il futuro è incerto, ma questa incertezza è la nostra salvezza.", author: "Anonimo" },
    { text: "Non è forte chi non cade, ma chi cade e si rialza.", author: "Anonimo" },
    { text: "Il potere di scegliere è tutto ciò che hai.", author: "Anonimo" },
    { text: "Il successo è la somma di piccoli sforzi ripetuti giorno dopo giorno.", author: "Anonimo" },
    { text: "Il modo per iniziare è smettere di parlare e iniziare a fare.", author: "Anonimo" },
    { text: "Non cercare la felicità. Creala.", author: "Anonimo" },
    { text: "La felicità è un viaggio, non una destinazione.", author: "Anonimo" },
    { text: "La vita è un eco. Ciò che mandi torna indietro.", author: "Anonimo" },
    { text: "La migliore vendetta è un successo enorme.", author: "Frank Sinatra" },
    { text: "Se non hai la capacità di fare grandi cose, puoi fare piccole cose con grande amore.", author: "Madre Teresa" },
    { text: "Il successo è ottenere quello che si vuole. La felicità è volere quello che si ottiene.", author: "Dale Carnegie" },
    { text: "La vera misura di un uomo è come tratta qualcuno che non può fargli nulla di buono.", author: "Samuel Johnson" },
    { text: "Sii grato per quello che hai, non sarai mai abbastanza felice per quello che vuoi.", author: "Anonimo" },
    { text: "L'unica cosa che si frappone tra te e il tuo sogno è la volontà di provarci.", author: "Anonimo" },
    { text: "Lavora duramente in silenzio, lascia che il successo sia il tuo rumore.", author: "Frank Ocean" },
    { text: "Non puoi usare la creatività. Più la usi, più ne hai.", author: "Maya Angelou" },
    { text: "La cosa più difficile di tutte è conoscere se stessi.", author: "Thales" },
    { text: "Fai sempre del tuo meglio. Ciò che pianti ora, raccoglierai dopo.", author: "Og Mandino" },
    { text: "Quando tutto sembra andare contro di te, ricorda che l'aereo decolla contro vento, non con esso.", author: "Henry Ford" },
    { text: "Il mondo è un libro, e chi non viaggia ne legge solo una pagina.", author: "Sant'Agostino" },
    { text: "Non piangere perché è finita, sorridi perché è successo.", author: "Dr. Seuss" },
    { text: "Non dire 'non ho tempo'. Dì 'non è la mia priorità'.", author: "Anonimo" },
    { text: "La fortuna favorisce la mente preparata.", author: "Louis Pasteur" },
    { text: "La qualità non è un atto, è un'abitudine.", author: "Aristotele" },
    { text: "Se non puoi correre, cammina. Se non puoi camminare, gattona. Ma non fermarti mai.", author: "Martin Luther King Jr." },
    { text: "La bellezza del mondo si trova nella diversità delle sue creature.", author: "Anonimo" },
    { text: "Il futuro non è qualcosa che si aspetta, ma qualcosa che si crea.", author: "Anonimo" },
    { text: "Ci sono montagne da scalare e sogni da realizzare.", author: "Anonimo" },
    { text: "Non è importante ciò che guardi, ma ciò che vedi.", author: "Henry David Thoreau" },
    { text: "La vita inizia alla fine della tua zona di comfort.", author: "Neale Donald Walsch" },
    { text: "Il successo è la somma di piccole vittorie quotidiane.", author: "Anonimo" },
    { text: "Il pensiero positivo ti renderà potente. L'azione positiva ti renderà inarrestabile.", author: "Anonimo" },
    { text: "Fai ciò che ti rende felice. Stai con chi ti fa sorridere. Ridi quanto respiri.", author: "Anonimo" },
    { text: "Il vero fallimento è smettere di provare.", author: "Anonimo" },
    { text: "Non è mai troppo tardi per essere ciò che hai sempre voluto essere.", author: "Anonimo" },
    { text: "Sii gentile. Tutte le persone che incontri stanno combattendo una battaglia che non conosci.", author: "Platone" },
    { text: "La conoscenza parla, ma la saggezza ascolta.", author: "Jimi Hendrix" },
    { text: "La vita è come andare in bicicletta. Per mantenere l'equilibrio devi continuare a muoverti.", author: "Albert Einstein" },
    { text: "Il tuo corpo può sopportare quasi tutto. È la tua mente che devi convincere.", author: "Anonimo" },
    { text: "Non cercare l'approvazione. Cerca di essere migliore.", author: "Anonimo" },
    { text: "La vita non ti dà quello che vuoi, ti dà quello di cui hai bisogno.", author: "Anonimo" },
    { text: "Il successo non è definitivo, il fallimento non è fatale: è il coraggio di continuare che conta.", author: "Winston Churchill" },
    { text: "Non è mai troppo tardi per iniziare a vivere la vita che hai sognato.", author: "Anonimo" },
    { text: "L'ottimismo è la fede che porta al successo.", author: "Helen Keller" },
    { text: "Non abbiamo bisogno della magia per cambiare il mondo, abbiamo già tutto il potere di cui abbiamo bisogno dentro di noi.", author: "J.K. Rowling" },
    { text: "Il genio è composto per l'1% di ispirazione e per il 99% di traspirazione.", author: "Thomas A. Edison" },
    { text: "La felicità è una scelta che richiede sforzo.", author: "Anonimo" },
    { text: "Sii una luce per gli altri.", author: "Anonimo" },
    { text: "Il ricordo di ciò che è stato, è un insegnamento per ciò che sarà.", author: "Anonimo" },
    { text: "La speranza è l'unica cosa più forte della paura.", author: "Suzanne Collins" },
    { text: "La strada per il successo e la strada per il fallimento sono quasi esattamente le stesse.", author: "Colin R. Davis" },
    { text: "Per avere qualcosa che non hai mai avuto, devi fare qualcosa che non hai mai fatto.", author: "Anonimo" },
    { text: "La tua determinazione a raggiungere il successo è più importante di qualsiasi altra cosa.", author: "Anonimo" },
    { text: "Non smettere mai di sognare, solo chi sogna può volare.", author: "Peter Pan" },
    { text: "La saggezza è l'arma più affilata.", author: "Anonimo" },
    { text: "Il vero viaggio di scoperta non consiste nel cercare nuovi paesaggi, ma nell'avere nuovi occhi.", author: "Marcel Proust" },
    { text: "La vita è troppo breve per sprecarla in lamentele.", author: "Anonimo" },
    { text: "Non c'è nulla di nobile nell'essere superiore a un altro uomo. La vera nobiltà è essere superiore al tuo io precedente.", author: "Ernest Hemingway" },
    { text: "L'amore è l'unica cosa che cresce quando viene divisa.", author: "Anonimo" },
    { text: "Il fallimento non è cadere, ma rifiutarsi di rialzarsi.", author: "Proverbio Cinese" },
    { text: "La più grande gloria nella vita non consiste nel non cadere mai, ma nel rialzarsi ogni volta che cadiamo.", author: "Nelson Mandela" },
    { text: "Il successo non è la destinazione, ma il viaggio.", author: "Zig Ziglar" },
    { text: "Il miglior investimento è in te stesso.", author: "Warren Buffett" },
    { text: "Sii un leader, non un seguace.", author: "Anonimo" },
    { text: "Non smettere di credere nei miracoli.", author: "Anonimo" },
    { text: "Il cambiamento inizia con la fine della tua zona di comfort.", author: "Anonimo" }
];
